name: Deploy Spring Boot to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: |
          cd gateway
          ./mvnw clean package -DskipTests
          mv target/*.jar target/app.jar
      
      
      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY_B64 }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: Copy artifact to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no \
            gateway/target/*.jar \
            ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app.jar

      - name: Run Spring Boot on EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
            pkill -f 'java -jar app.jar' || true
            nohup java -jar /home/ec2-user/app.jar > /home/ec2-user/app.log 2>&1 &
            tail -n 20 /home/ec2-user/app.log
          "
